### PR TITLE
adapt for x64, cmake and appveyor config

### PR DESCRIPTION
**Pull request by chcg**
- version with build of 3rd party libs under msvc on appveyor CI, see https://ci.appveyor.com/project/chcg/nppftp/build/0.26.6.56, you need to register this github project at appveyor to enable it for their CI builds
- cmake config for nppftp code itself
- added include for shellapi.h, not included if WIN32_LEAN_AND_MEAN is defined, like done for optimization purposes in cmake config file
- added no-shared also for msvc openssl build
- added msvc_x64 target to build_3rdparty.py and added the option to choose the target via commandli´ne option

Some open issue:
- appveyor config doesn't work for mingw-w64, seems build_3rdparty.py is not prepared to run mingw-w64 on windows and appveyor has in the current config no unix make in the path, therefore it is switched off currently
- build_3rdparty.py is not prepared for debug builds. Is this intentional?
- build_3rdparty.py is not prepared for mingw-w64 x86_64
- appveyor has from time to time problems with the download, I didn't see this issues on using git submodules, did some tests\adaptations on submodule usage in https://github.com/chcg/NppFTP/tree/appveyor

### CODE REVIEW

**Comment by ashkulz** [comment]
Can you let me know what errors you are getting in the mingw-w64 build? I'd prefer to use that, as there is no dependency on the VC runtime.

**Comment by chcg** [comment]
Needs a little bit more tweaking, see https://ci.appveyor.com/project/chcg/nppftp/build/4.2.1.18

Issue:

python : 'make' is not recognized as an internal or external command,
At line:5 char:1
+ python build_3rdparty.py mingw-w64
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ashkulz** [comment]
@chcg: although I certainly would like to have the MSVC build, I feel the MinGW build is equally important. If it is not too much trouble, can you make a Travis CI configuration which checks the MinGW build? See the reason mentioned above about standalone build.

**Comment by chcg** [comment]
I will try both, get the appveyor build ready for mingw and checkout how this could be done with a travis build and which sw packages are missing there. For https://github.com/jsleroy/compare-plugin/blob/master/.travis.yml it was harder to get the config right than for appveyor, but we will see.

**Comment by ashkulz** [comment]
I think the travis build should be easy to set up, see `BUILDING.md`. I'm pretty sure it'll work with Trusty instead of Xenial, which is what I've built it on (you may need to install `python3`).

**Comment by ashkulz** [comment]
@chcg: thanks for the pointer, it was very easy to setup the Travis CI build. It should automatically [build and upload on releases](https://travis-ci.org/ashkulz/NppFTP/builds/180640468) as well. I'd recommend that you drop the mingw build on Windows and just focus on the MSVC build for AppVeyor after rebasing your changes.

**Comment by chcg** [comment]
Nice work. New tag works for me in x64. I will rebase with your changes.

**Comment by ashkulz** [comment]
Hmm. I'd like, in order of preference:

1. a single build system i.e. cmake covering msvc + mingw (windows / linux)
2. Ditto, but for msvc + mingw linux -- dropping mingw windows
3. Current for mingw linux plus msvc only for Windows (removing mingw parts)

Not sure if cmake can work that way (calling build.py) so you decide whats possible...

**Comment by chcg** [comment]
Forgot to mention my test build on travis, see:

https://travis-ci.org/ashkulz/NppFTP/builds/180986307

, so cmake config is ready to build with mingw linux. What is missing is the integration of the build_3rdparty.py call (should be possible via add_custom_command) and the packaging as zip for the deployment

**Comment by ashkulz** [comment]
@chcg: that's great! but it looks like it generated `libNppFTP.dll` instead. If possible, can you split into two PRs:

1. Replace `Makefile.mingw` with cmake, integrated with Travis (without any MSVC stuff).
2. Add changes for MSVC with AppVeyor

That'll be easier to review and verify.

**Comment by chcg** [comment]
See https://ci.appveyor.com/project/chcg/nppftp/build/0.26.7.101. Updated cmake to call python script. Zipping still missing.

I will check how I could split it up and whar is the issue with libNppFTP.dll

**Comment by ashkulz** [comment]
Thanks!

**Comment by chcg** [comment]
Close this one here in favour of clean single commit in #133.

**Pull request closed without merging**
