### PR TITLE
NppFTP multi tabs (for multi ftpsite)

### PR DESCRIPTION
**Pull request by ysoudy**
Hi,

I'm working on several FTP sites on the same time, and I need to Disconnect / Reconnect each time I need to change.
If you can create "tabs" for each ftp site, it will be awesome..

Please see a prototype below : 
image

### CODE REVIEW

**Comment by vlakoff** [comment]
As a workaround, you can run multiple instances of Notepad++ ;-)

    "C:\Program Files (x86)\Notepad++\notepad++.exe" -multiInst

Another way: right-clic on file tab > Move to New Instance / Open in New Instance

**Comment by ysoudy** [comment]
I use already this workaround (thx anyway ;)
and it's not very useable : hard to know exactly in which instance you are (perhaps if I was able to define a different background color... )

**Comment by ashkulz** [comment]
This looks like an issue, not a PR.

**Comment by ysoudy** [comment]
It's not an issue... juste a good idea to improve NppFtp ;)
please dont close it !

**Pull request closed without merging**
