### PR TITLE
Add Feature Chmod File and Directory

### PR DESCRIPTION
**Pull request by mean-cj**
Hello everybody
I've been waiting for this day for a long time.
- Add Feature Chmod File and Directory for NppFTP

Enter your permission into input
Example 755 or 0755 , 644 or 0644

Have a nick days.
Mean-CJ

### CODE REVIEW

**Comment by ashkulz** [comment]
can you rebase your changes on top of the latest `master` and squash your commits? A lot of the commits don't make sense in isolation.

**Comment by muggy8** [comment]
Did this make it into the official notepad++ repo? If so how do i get use it? (right click? settings?)

Thanks!

**Comment by ashkulz** [comment]
Nope, they didn't -- there were a lot of changes which didn't make sense.

**Comment by chcg** [comment]
@mean-cj Do you still want to care about this PR to get it into a mergeable state?

**Comment by chcg** [comment]
@mean-cj Do you still want to care about this PR to get it into a mergeable state?

**Pull request merged**
