### PR TITLE
Added 64-bit build scripts

### PR DESCRIPTION
**Pull request by nerddtvg**
Added two build files for 64-bit. Tested only with Linux mingw64 compilers.

Modified uh_ctrl to reference long long for HWND pointers.

Changed the Makefile64.mingw file to remove -Wall as it threw errors on calling functions with return values that were unused.

### CODE REVIEW

**Comment by nerddtvg** [comment]
@ashkulz ,

Oh wow. I was really out of it this morning I guess.

* I would love to combine them, but this isn't my specialty. I figured having a base would be a good start. I'd love to see a single build script (deps and all) and use a build flag to specify which architecture to use.
* RE: uh_ctrl, Yeah, I'll resubmit in a little while.
* RE: Wall, Only a few regarding the src/Windows/ProfilesDialog.cpp file and TabCtrl_* and ListView_* functions. Most of these return a bool or int and since it isn't stored in a variable (despite never being used anyways), it threw the error/warning.
* RE: template, I didn't even know about that. I just needed to use the plugin and hacked it together for today. I'll look into that later on.

Thank you

**Comment by chcg** [comment]
Hi, you could countercheck with the x64 changes in #115. The msvc x64 build was running fine with 7.2.1 n++ on some simple tests, so no immediate crashes, but that needs surely more widespreaded and comprehensive tests.

**Comment by ashkulz** [comment]
@nerddtvg: I've committed a generic build script which should work for both 32-bit and 64-bit.

@chcg: I've taken your `LRESULT` fix while I've used the other fix from @nerddtvg for getting the 64-bit compilation working. You'll probably need to rebase #115 after these changes.

**Comment by ashkulz** [comment]
Forgot to say, thanks a lot @nerddtvg!

**Comment by nerddtvg** [comment]
Thank you for doing this. I rely on this plugin all the time and just felt I could at least give back something.

**Comment by ashkulz** [comment]
Well, your and @chcg PRs motivated me to spend an evening on this 👍

**Pull request closed without merging**
